/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ccuk.demo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        DemoApplication classUnderTest = new DemoApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
